const {PGlite}=await import(process.env.PGLITE_MODULE || '@electric-sql/pglite');
import {readFile} from 'node:fs/promises';
import assert from 'node:assert/strict';
const db=new PGlite();
await db.exec(`create role anon;create role authenticated;create role service_role bypassrls;
create schema supabase_migrations;create table supabase_migrations.schema_migrations(version text);
insert into supabase_migrations.schema_migrations values ('20260923110406');
create function public.es_admin() returns boolean language sql as $$ select current_setting('test.admin',true)='yes' $$;
grant usage on schema public to anon,authenticated,service_role;
create table public.test_no_rls(id int);`);
await db.exec(await readFile(new URL('../../supabase/migrations/20260923155000_weekly_audit_reports.sql',import.meta.url),'utf8'));
await db.exec(`set role service_role;insert into public.weekly_audit_reports(id,kind,scheduled_date,status,report,markdown) values('seo-2026-09-24','seo','2026-09-24','complete','{}','Prueba');`);
const snapshot=await db.query('select public.weekly_audit_security_snapshot() as s');assert.ok(snapshot.rows[0].s.tables_without_rls.includes('test_no_rls'));assert.equal(snapshot.rows[0].s.tables_without_rls.includes('weekly_audit_reports'),false);
await db.exec(`reset role;set role authenticated;select set_config('test.admin','no',false);`);
assert.equal((await db.query('select * from public.weekly_audit_reports')).rows.length,0);
await assert.rejects(()=>db.query('select public.weekly_audit_security_snapshot()'));
await assert.rejects(()=>db.exec(`delete from public.weekly_audit_reports`));
await db.exec(`select set_config('test.admin','yes',false)`);
assert.equal((await db.query('select * from public.weekly_audit_reports')).rows.length,1);
await db.exec(`reset role;set role anon;`);
await assert.rejects(()=>db.query('select * from public.weekly_audit_reports'));
console.log('SQL: migración ejecutada; admin lee, usuario normal sin filas, anon denegado; escritura/snapshot restringidos.');
await db.close();
